### ISSUE TITLE
bodhi datagrepper leaks email address

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/datagrepper#157]
Steps to reproduce:
1. Find a update submitted to bodhi, e.g. https://admin.fedoraproject.org/updates/NetworkManager-0.9.10.0-13.git20140704.fc21
2. add a comment; leave your email address in the "email address" field; submit comment

What happens:
Datagrepper leaks your email address: https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.comment
this also affects apps.fp.o:
https://apps.fedoraproject.org/packages/NetworkManager (under history)
and possibly other sites.

**Comment by genodeftest** [comment]
Is there a way I can get my email address removed from old fedmsg messages? I have a specific URL but don't want to post it to not increase the spam volume even more.

**Comment by ralphbean** [comment]
@genodeftest email admin@fedoraproject.org with the request.

**Comment by genodeftest** [comment]
@ralphbean Thank you!
