### ISSUE TITLE
autoscroll doesn't work on chrome

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/datagrepper#173]
it works in firefox though.  If you visit https://apps.fedoraproject.org/datagrepper/raw and scroll down, it should auto-load more results (forever).

**Comment by sayanchowdhury** [comment]
Came here to report the same issue. I think this is because of the javascript issue with Content-Security-Policy in chrome. I see it's already resolved in the develop branch - http://git.io/v32GU

**Comment by ralphbean** [comment]
Yeah, this seems to be working now.  :)
