### ISSUE TITLE
time-out

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/datagrepper#178]
Looks like datagrepper isn't happy with my query:
https://apps.fedoraproject.org/datagrepper/raw/?topic=org.fedoraproject.prod.pkgdb.package.delete

But we do publish these messages (although rarely I agree):
https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/tests/pkgdb.py#L786

**Comment by ralphbean** [comment]
Does it help to query for only one at a time?  https://apps.fedoraproject.org/datagrepper/raw/?topic=org.fedoraproject.prod.pkgdb.package.delete&rows_per_page=1&order=asc

**Comment by pypingou** [comment]
Indeed, up to 10 seems to work: https://apps.fedoraproject.org/datagrepper/raw/?topic=org.fedoraproject.prod.pkgdb.package.delete&rows_per_page=10&order=asc (and seems there are only 7 of these messages in our DB)

**Comment by ralphbean** [comment]
OK, I'm going to close this one.  This is a reasonable situation to time out in... (since it has to search through everything to find those last few messages that don't exist).
