### ISSUE TITLE
show timezone in timestamps

### ISSUE THREAD

**Issue by kparal** [fedora-infra/datagrepper#181]
When I look at some listing ([example](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.updates.fedora.sync)) I sometimes need to know which timezone all the timestamps are in. I can open the JSON and convert the unix timestamp, but it would be much easier for people if you could show it right away. Since it seems all the timestamps are in UTC, what about simply appending "UTC" suffix to the timestamp string? Thanks.

**Comment by ralphbean** [comment]
They are in fact all in UTC.  That makes this an "easyfix" to just add the string "UTC" in the template.

**Comment by userimack** [comment]
I will like to work on it.
