### ISSUE TITLE
Wrong user after FAS change

### ISSUE THREAD

**Issue by athos-ribeiro** [fedora-infra/datagrepper#186]
After changing my FAS username from 'ribeiro' to 'athoscr' (I created a new FAS and moved my primary email from the 1st to the 2nd account) some notifications, like bugzilla activity, are still shown for the former user and not shown for the new one. 

Is this a problem with datagrepper or somewhere else in the infrastructure?

**Comment by pypingou** [comment]
This could be a configuration change required at FMN: https://apps.fedoraproject.org/notifications

**Comment by athos-ribeiro** [comment]
Do you mean for both FAS accounts I own or in the FMN itself? I already disabled all notifications from my former account (even before opening this issue).

**Comment by pypingou** [comment]
I am a little bit flying blind here as I do not know which notifications you're talking about.

But one thing is sure, they are not coming from datagrepper since that one doesn't send anything.

FMN is likely the culprit here but it might require checking it a little further.

**Comment by athos-ribeiro** [comment]
bugzilla and irc meetings notifications, for example,  still go to the old FAS https://apps.fedoraproject.org/datagrepper/raw?user=ribeiro

instead of the new one https://apps.fedoraproject.org/datagrepper/raw?user=athoscr

**Comment by pypingou** [comment]
I'll need more than that to help figuring out where the notifications are coming from, but it's most likely FMN.

**Comment by pypingou** [comment]
Is this still happening?

**Comment by pypingou** [comment]
I am going to close this ticket for now, feel free to re-open it if it still happens, or to ping one of us on IRC

Thanks for your report :)

**Comment by athos-ribeiro** [comment]
Hi Pingou,
Sorry for the slow response rate, was busy @ FUDCon Puno.

After nb refreshed zodbot cache, IRC  notifications started going to the right username. Bugzilla notifications still go to the other user (ribeiro instead of athoscr)

https://apps.fedoraproject.org/datagrepper/raw?user=ribeiro
https://apps.fedoraproject.org/datagrepper/raw?user=athoscr

**Comment by pypingou** [comment]
Let's re-open then, but do know that those two links don't provide much info to us

**Comment by athos-ribeiro** [comment]
Just for the records, email and irc settings are disabled for the old account in https://apps.fedoraproject.org/notifications/ and are enabled for the new account.
