### ISSUE TITLE
`newrev` is a python object

### ISSUE THREAD

**Issue by frozencemetery** [fedora-infra/datagrepper#215]
Hi, in some queries I'm seeing:

                "newrev": "<_pygit2.Tag object at 0x7f02afc42bd0>",

in the json output (Red Hat instance).  I imagine this isn't datagrepper's fault but I don't know where to properly assign it.  Thanks!

**Comment by pypingou** [comment]
We would need more information, but if this is an RH internal instance @ralphbean is probably the right person to poke for help :)

**Comment by jeremycline** [comment]
If I were to guess, I'd say whatever is sending that message is failing to properly serialize it to JSON before sending it. I imagine it's supposed to be the git tag, but it's calling ``__repr__`` or something and that's not implemented as the caller expects.

Whatever app is creating the message is probably the right place to file the issue.
