### ISSUE TITLE
handle unicode in user names

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/datagrepper#235]
Datagrepper shows a list of authors here: https://apps.fedoraproject.org/datagrepper/id?id=2021-70512a4b-0f45-431b-9c3c-f081032c9d86&is_raw=true&size=extra-large

It shows @hroncok's name as "Miro Hron\u010dok" instead of "Miro Hrončok"

**Comment by hroncok** [comment]
That is proper json thou.

**Comment by pypingou** [comment]
which probably makes the issue invalid then as the part in yellow is just the JSON as is
