### ISSUE TITLE
Make the json returned by datagrepper (/raw and /id ) as close as possible to what is currently returned*

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/datagrepper#265]
the order of keys is slightly different (does this matter really) and we dev datagrepper returns 2 extra keys -- users and packages.

**Comment by ryanlerch** [comment]
Ok, from what i can gather, there are 3 differences here that we need to decide if we need to do anthing about.

1. the order of the keys. currently the current live, fedmsg - based datagrepper returns the following items:
```
  "username"
  "source_name"
  "certificate"
  "i"
  "timestamp"
  "msg_id"
  "crypto"
  "topic"
  "headers"
  "signature"
  "source_version"
  "msg"
```
while the development datagrepper using the fedora-messaging datanommer models returns the following order:
```
  "i"
  "msg_id"
  "topic"
  "timestamp"
  "certificate"
  "signature"
  "username
  "crypto"
  "msg"
  "headers"
  "source_name"
  "source_version"
  "users"
  "packages"
```
note that there are also 2 extra keys in this one, `packages` and `users` The question here is does the order of these keys matter? since users are (hopefully) just parsing this as json, and the order shouldnt matter.
2. With the additional keys, `packages` and `users` do we need to drop them for the current raw and id endpoints? obviously, these will be included in the fedora-messaging endpoints when they are implemented.
3. fedmsg prefixes message id's with the year. The fedmsg -> fedoramessaging bridge also does this. So currently on developement datanommer / datagrepper, we are getting a mix of msgid styles:
* a fedora-messaging message sent to the fedora-messaging queue doenst have the year prefix.
* a fedmsg message that passes over the bridge has the year prefix

**Comment by ryanlerch** [comment]
FYI, the following gist has example json ourput from datanommer for stable and dev. There are 2 differrent messages there, one fedmsg native one (the wiki one) that has passed over the bridge, and one fedora-messaging native one.

https://gist.github.com/ryanlerch/61eb9accdc6476b2b1d0c8e6d322f122

**Comment by ryanlerch** [comment]
for the ordering of the keys, changing the order in the datanommer.models, as_dict() method works -- just not sure if we want to do it there, or in datagrepper itself (or at all)

**Comment by abompard** [comment]
It may be too much of a slowdown to prefix msg_ids with the year when getting them from the DB, so maybe don't touch them.

**Comment by ryanlerch** [comment]
So, i think there is not anything left to do on this one.

The order of the keys in the JSON shouldnt matter. 
WE are not removing any items in the JSON -- only adding 2 new ones -- users and packages.

so closing this one as done.
