### ISSUE TITLE
Add a link to the list of available messages

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datagrepper#291]
There's a list of known messages [on the fedora-messaging documentation](https://fedora-messaging.readthedocs.io/en/stable/schemas.html). It would be nice to have a link to that list in Datagrepper's footer.

**Comment by archijaiswal** [comment]
@abompard I would like to work on this.

**Comment by ghost** [comment]
@abompard How does this sound to be appended to footer?

          View <a href="https://fedora-messaging.readthedocs.io/en/stable/user-guide/schemas.html">available messages</a>.
