### ISSUE TITLE
problems since Datanommer migration

### ISSUE THREAD

**Issue by bretth25** [fedora-infra/datagrepper#293]
Hi

Since the migration, the following query returns no records when there should be 100's - https://apps.fedoraproject.org/datagrepper/raw?user=bretth&topic=org.fedoraproject.prod.bodhi.update.comment

A query for bretth records returns none -  https://apps.fedoraproject.org/datagrepper/raw?user=bretth

A query for bodhi records returns a screen full then stalls - https://apps.fedoraproject.org/datagrepper/raw?user=bodhi

This query returns 3 records and stalls - https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.comment

The following query was returning records yesterday but isn't today - https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.request.stable

I see the migration is marked complete but these queries have worked fine for ages and have had problems since the migration.

Anything I can do to help sot this out ?

Thanks

**Comment by bretth25** [comment]
i just noticed that recent bodhi comments are showing up in my profile so it appears new data is being ingested and the queries aren't finding both new and pre-migration data..

**Comment by bretth25** [comment]
I've made some progress on this. It appears that since the migration a time delta has been added as a default request parameter so that only records in the last 1hr (3600 sec) are returned. Previously, you could scroll down thru the page in the browser and more data would be returned each time until all records has been shown.

Also, it appears that the query format has changed. The old format (used above) still works for now. The new format equivalent of a working old format query (replace raw above with v2/search)  is consistently  throwing: ERROR 500: INTERNAL SERVER ERROR

An initial look at that problem shows the new format works with rows_per_page=1 or 2 but throws the 500 error with rows_per_page=3 or larger.  Buffer size problem perhaps ?

**Comment by abompard** [comment]
Hey, thanks for reporting all this.
Indeed there is now a default delta, but we announced it to be 1 day and it was actually set to one hour as you noticed. I fixed this, it's now one day.
I have also fixed the error that happened with the `v2/search` endpoint, it does not traceback anymore. It happened because some of the messages were missing headers, and datagrepper didn't handle that well.

**Comment by bretth25** [comment]
Confirm working now. Thanks a lot for your help.

Should I close it now or do you need to do that?

**Comment by abompard** [comment]
Yeah I'll close it, thanks.
