### ISSUE TITLE
Split datagrepper into subpackages

### ISSUE THREAD

**Issue by ianweller** [fedora-infra/datagrepper#56]
After a discussion with @ralphbean we decided we should split up datagrepper into subpackages, similar to datanommer, so that the job runner can run on a different server than the web server.

Packages will be split as follows:
- datagrepper.models
- datagrepper.web
- datagrepper.runner

**Comment by ralphbean** [comment]
Eh, this isn't necessary after #158 since now datagrepper has no model of its own, and no runner.  Only a web interface to the datanommer.models db.
