### ISSUE TITLE
bulk queries do not work / require authentication

### ISSUE THREAD

**Issue by tyll** [fedora-infra/datagrepper#99]
The following request does not work, but should according to the documentation:
    
    $ http get https://apps.fedoraproject.org/datagrepper/submit/ delta==3600
    HTTP/1.1 400 BAD REQUEST
    Connection: close
    Content-Length: 19
    Content-Type: application/json
    Date: Sat, 21 Dec 2013 17:58:40 GMT
    ProxyServer: proxy04.fedoraproject.org
    ProxyTime: D=158456
    Server: Apache/2.2.15 (Red Hat)
    
    {
        "error": "no_auth"
    }

**Comment by ralphbean** [comment]
This got removed in #158.
